# MPDB basic configuration
mpdb.version = @application.version@
spring.datasource.username=root
spring.datasource.password=phulay
spring.datasource.url=jdbc:mysql://localhost:3306/maple
spring.jpa.hibernate.ddl-auto=update
server.port=8081
